package com.regional.property.model;

// Generated 16 Oct, 2016 5:51:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Sector generated by hbm2java
 */
@Entity
@Table(name = "sector", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "sector_name"))
public class Sector implements java.io.Serializable {

	private int sectorId;
	private Ward ward;
	private String sectorName;
	private int deleted;
	private Date created=new Date();
	private Date lastUpdate=new Date();
	private Set<Plot> plots = new HashSet(0);

	public Sector() {
	}

	public Sector(int sectorId, Ward ward, String sectorName, int deleted,
			Date created, Date lastUpdate) {
		this.sectorId = sectorId;
		this.ward = ward;
		this.sectorName = sectorName;
		this.deleted = deleted;
		this.created = created;
		this.lastUpdate = lastUpdate;
	}

	public Sector(int sectorId, Ward ward, String sectorName, int deleted,
			Date created, Date lastUpdate, Set plots) {
		this.sectorId = sectorId;
		this.ward = ward;
		this.sectorName = sectorName;
		this.deleted = deleted;
		this.created = created;
		this.lastUpdate = lastUpdate;
		this.plots = plots;
	}

	@Id
	@Column(name = "sector_id", unique = true, nullable = false)
	public int getSectorId() {
		return this.sectorId;
	}

	public void setSectorId(int sectorId) {
		this.sectorId = sectorId;
	}

	@ManyToOne
	@JoinColumn(name = "ward_id", nullable = false)
	@JsonIgnore
	public Ward getWard() {
		return this.ward;
	}

	public void setWard(Ward ward) {
		this.ward = ward;
	}

	@Column(name = "sector_name", unique = true, nullable = false, length = 100)
	public String getSectorName() {
		return this.sectorName;
	}

	public void setSectorName(String sectorName) {
		this.sectorName = sectorName;
	}

	@Column(name = "deleted", nullable = false)
	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", nullable = false, length = 29)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
	 @LazyCollection(LazyCollectionOption.FALSE)
	@OneToMany(mappedBy = "sector")
	@JsonIgnore
	public Set<Plot> getPlots() {
		return this.plots;
	}

	public void setPlots(Set<Plot> plots) {
		this.plots = plots;
	}

}
