package com.regional.property.model;

// Generated 9 Oct, 2016 8:53:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "user_roles", schema = "public")
public class UserRoles implements java.io.Serializable {

	private int userRoleId;
	private Role role;
	private RegUsers regUsers;
	private int deleted=0;
	private Date created=new Date();
	private Date lastUpdate=new Date();
	public UserRoles() {
	}

	public UserRoles(int userRoleId, Role role, RegUsers regUsers, int deleted,
			Date created, Date lastUpdate) {
		this.userRoleId = userRoleId;
		this.role = role;
		this.regUsers = regUsers;
		this.deleted = deleted;
		this.created = created;
		this.lastUpdate = lastUpdate;
	}

	@Id
	@Column(name = "user_role_id", unique = true, nullable = false)
	@SequenceGenerator(
			name="user_roles_sequence",
			sequenceName="user_roles_seq",initialValue=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="user_roles_sequence")
	public int getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public RegUsers getRegUsers() {
		return this.regUsers;
	}

	public void setRegUsers(RegUsers regUsers) {
		this.regUsers = regUsers;
	}

	@Column(name = "deleted", nullable = false)
	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", nullable = false, length = 29)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
