package com.regional.property.model;

// Generated 16 Oct, 2016 5:51:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Ward generated by hbm2java
 */
@Entity
@Table(name = "ward", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "ward_name"))
public class Ward implements java.io.Serializable {

	private int wardId;
	private String wardName;
	private int deleted;
	private Date created=new Date();
	private Date lastUpdate=new Date();
	private Set<Sector> sectors = new HashSet(0);

	public Ward() {
	}

	public Ward(int wardId, String wardName, int deleted, Date created,
			Date lastUpdate) {
		this.wardId = wardId;
		this.wardName = wardName;
		this.deleted = deleted;
		this.created = created;
		this.lastUpdate = lastUpdate;
	}

	public Ward(int wardId, String wardName, int deleted, Date created,
			Date lastUpdate, Set sectors) {
		this.wardId = wardId;
		this.wardName = wardName;
		this.deleted = deleted;
		this.created = created;
		this.lastUpdate = lastUpdate;
		this.sectors = sectors;
	}

	@Id
	@Column(name = "ward_id", unique = true, nullable = false)
	public int getWardId() {
		return this.wardId;
	}

	public void setWardId(int wardId) {
		this.wardId = wardId;
	}

	@Column(name = "ward_name", unique = true, nullable = false, length = 100)
	public String getWardName() {
		return this.wardName;
	}

	public void setWardName(String wardName) {
		this.wardName = wardName;
	}

	@Column(name = "deleted", nullable = false)
	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", nullable = false, length = 29)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

    @LazyCollection(LazyCollectionOption.FALSE)
	@OneToMany(mappedBy = "ward")
	@JsonIgnore
	public Set<Sector>  getSectors() {
		return this.sectors;
	}

	public void setSectors(Set<Sector>  sectors) {
		this.sectors = sectors;
	}

}
